<a href="https://colab.research.google.com/github/Tarunagg1/Letsupgrade_DataScience/blob/main/datascienceday3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
# question 1
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [18]:
# question 2
list1 = []
list2 = []

for i in range(0,5):
  list1.append(int(input("enter the number: ")))
  
for i in range(0,5):
  list2.append(int(input("enter the number: ")))

arr = np.array([list1,list2])
print(arr)
print("After sorting")
print(np.sort(arr))


enter the number: 82
enter the number: 49
enter the number: 18
enter the number: 48
enter the number: 18
enter the number: 4
enter the number: 81
enter the number: 48
enter the number: 58
enter the number: 84
[[82 49 18 48 18]
 [ 4 81 48 58 84]]
After sorting
[[18 18 48 49 82]
 [ 4 48 58 81 84]]


In [20]:
# question 3
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Dimension of array")
print(arr.shape)
print("size of array")
print(arr.size)


Dimension of array
(2, 4)
size of array
8


In [44]:
# question 4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr,'\n')
arr_2d = np.reshape(arr, (2, 5))
print('After 2D conversion Numpy array:')
print(arr_2d)


1D Numpy array:
[0 1 2 3 4 5 6 7 8 9] 

After 2D conversion Numpy array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [43]:
# question 5
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[8,7,6,5],[4,3,2,1]])

print(np.hstack(arr1),"\n")

print(np.vstack(arr1))


[1 2 3 4 5 6 7 8] 

[[1 2 3 4]
 [5 6 7 8]]


In [36]:
# question 6
arr = np.array([1, 1, 2, 3, 4, 4, 1])
#print(arr)
(unique, counts) = np.unique(arr, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)


[[1 3]
 [2 1]
 [3 1]
 [4 2]]
